



## Load library
```{r}
library(tidyverse)
library(ggpubr)
library(readxl)
library(here)
library(janitor)

source(here("article_theme.R"))
source(here("Benchmarking", "functions.R"))
```

## Load metadata

```{r}
extraction_benchmark_v1 <- read_excel(path = here("Benchmarking", "data", "ext_standard_samples_v1.2.xlsx")) %>%
    filter(kit != "PowerSoil Pro HT, 125") %>%
    mutate(benchmark = "v1") %>%
    clean_names() %>%
    rename(conc_qubit = conc_quibit)

extraction_benchmark_v2 <- read_excel(here("Benchmarking", "data", "Amplicon_metadata.xlsx")) %>%
    filter(!is.na(Kit)) %>%
    mutate(benchmark = "v2") %>%
    rename(conc_qubit = Conc_quibit) %>%
    clean_names()

benchmark_v2_input <- read_excel(here("Benchmarking", "data", "protocol_max_input.xlsx"), sheet = 2)

soil_types <- unique(extraction_benchmark_v1$soil_type)
soil_lvls <- c("Activated sludge", "Beach sand", "Clay", "Organic", "Sand", "Sand-clay", "Blank")
```

### Process metadata

```{r}
df_factored_v1 <- extraction_benchmark_v1 %>%
    mutate(soil_type_fct = factor(soil_type, levels = soil_lvls)) %>%
    mutate(
        kit = str_replace(kit, ", Ref", ""),
        kit = str_replace(kit, "FastDNA", "FastSpin"),
        kit = str_replace(kit, "Wagma", "MIDAS HT"),
        buffer_input = if_else(str_detect(kit, " HT"), 550, 1375)
    ) %>%
    select(benchmark, kit, soil_type, soil_type_fct, sample_target, buffer_input, x260_280, x260_230, conc_qubit)

df_factored_v2 <- extraction_benchmark_v2 %>%
    mutate(soil_type_fct = factor(soil_type, levels = soil_lvls)) %>%
    mutate(
        kit = str_replace(kit, ", Ref", ""),
        kit = str_replace(kit, ", ", " "),
        kit = str_replace(kit, "Midas", "MIDAS"),
        soil_type = str_replace(soil_type, "BLANK", "Blank")
    ) %>%
    left_join(benchmark_v2_input) %>%
    select(benchmark, kit, soil_type, soil_type_fct, sample_target, buffer_input, x260_280, x260_230, conc_qubit)

df_factored_combined <- bind_rows(df_factored_v1, df_factored_v2)
```

```{r}
df_factored_long <- df_factored_combined %>%
    filter(!soil_type %in% c("Activated sludge", "Blank")) %>%
    pivot_longer(x260_280:conc_qubit, names_to = "metric", values_to = "value") %>%
    mutate(metric = factor(metric, levels = c("conc_qubit", "x260_280", "x260_230"), labels = c("DNA conc [ng/µl] (Qubit)", "260/280 ratio", "260/230 ratio")))
```


## Plot
### experiment table
```{r}
experiment_table <- df_factored_combined %>%
    select(benchmark, kit, sample_target, buffer_input) %>%
    group_by(benchmark) %>%
    distinct(kit, .keep_all = TRUE) %>%
    arrange(benchmark, kit) %>%
    mutate(ratio = round(buffer_input / sample_target))

hjustification_matrix <- as.vector(matrix(c(0, 0, 1, 1, 1), ncol = 5, nrow = nrow(experiment_table), byrow = TRUE))
xjustification_matrix <- as.vector(matrix(c(0.1, 0.1, 0.9, 0.9, 0.9), ncol = 5, nrow = nrow(experiment_table), byrow = TRUE))



gg_exp_table <- experiment_table %>%
    mutate(benchmark = if_else(kit == "FastSpin", benchmark, "")) %>%
    ggtexttable(
        cols = c("", "Kit", "Sample input [mg]", "Buffer [µL]", "Buffer:Sample ratio"),
        rows = NULL,
        theme = ttheme(
            colnames.style = colnames_style(fill = "white"),
            tbody.style = tbody_style(
                fill = "white",
                hjust = hjustification_matrix,
                x = xjustification_matrix
            )
        )
    ) %>%
    tab_add_vline(at.column = 1, column.side = "right") %>%
    tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 2) %>%
    tab_add_hline(at.row = 8, row.side = "top", linewidth = 1)

gg_exp_table_with_dummy <- ggarrange(gg_exp_table, NULL, nrow = 2, heights = c(1, 0.3))
```

```{r}
gg_DNA_v1 <- df_factored_long %>%
    filter(benchmark == "v1") %>%
    createGGMetricsPlotForCombined(metric_filter = "DNA conc [ng/µl] (Qubit)") +
    labs(x = "", y = "", title = "Experiment v1: DNA concentration [ng/µl] (Qubit)") +
    theme(legend.position = "none")
```



```{r}
gg_280 <- createGGMetricsPlotForCombined(df_factored_long, metric_filter = "260/280 ratio") +
    coord_cartesian(ylim = c(0, 4)) +
    geom_hline(yintercept = 1.8, linetype = "dashed") +
    labs(x = "", y = "", title = "Nanodrop 260/280 ratio") +
    annotate(geom = "text", label = "Optimal 260/280 ratio", x = 2, y = 1.2, size = 4) +
    annotate(
        geom = "segment", x = 2, xend = 2, y = 1.3, yend = 1.7, linewidth = 1,
        arrow = arrow(length = unit(.5, "cm"))
    )

gg_230 <- createGGMetricsPlotForCombined(df_factored_long, metric_filter = "260/230 ratio") +
    coord_cartesian(ylim = c(0, 2.5)) +
    geom_hline(yintercept = 2.2, linetype = "dashed") +
    labs(x = "", y = "", title = "Nanodrop 260/230 ratio") +
    annotate(geom = "text", label = "Optimal 260/230 ratio", x = 2, y = 2.3, size = 4)
```


```{r}
gg_exp_DNA <- ggarrange(gg_exp_table_with_dummy, gg_DNA_v1, ncol = 2, labels = c("A", "B"))
gg_qual <- ggarrange(gg_280, gg_230, ncol = 2, labels = c("C", "D"), common.legend = TRUE, legend = "bottom")

ggarrange(gg_exp_DNA, gg_qual, nrow = 2)
```



```{r}
ggsave(here("Benchmarking", "figures", "DNA_extraction_characteristics_combined.png"), width = 13, height = 11)
```
