---
title: "Amplicon diversity of MFD standard samples 2.0"
author: "Thomas Bygh Nymann Jensen, Thomas Y. Michaelsen"
date: "`r format(Sys.time(), '%d-%m-%Y')`, Aalborg, Denmark"
output: 
  bookdown::html_document2:
    toc: true
---

```{r setup, include=FALSE}
library(knitr)
library(here)
knitr::opts_chunk$set(
  echo    = F,
  # fig.pos = "H",
  message = FALSE,
  warning = FALSE
)

setwd(here("Amplicon_scaledown"))

# Load the needed packages.
library(data.table)
library(readxl)
library(tidyverse)
library(ampvis2)
library(vegan)
library(patchwork)
library(ggpubr)

### Load and tidy ###
source("loaddata.R")
colors <- c("grey", "darkgoldenrod2", "royalblue4", "seagreen", "salmon", "purple")

### Load plot functions and theme
source("./functions.R")
```

## QC - PCR controls

```{r}
dat_PCR <- amp_subset_samples(datraw, is.na(Kit))

tabReads <- merge(
  dat_PCR$metadata,
  data.frame(NoReads = apply(dat_PCR$abund, 2, sum)),
  by = 0
)

ggplot(tabReads, aes(x = LibID, y = NoReads, colour = LibID)) +
  geom_jitter(width = .1) +
  labs(colour = "PCR controls", x = "", y = "# of reads") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## QC - blanks

```{r}
dat_blank <- amp_subset_samples(datraw, Soil_type == "Blank")

tabReads <- merge(
  dat_blank$metadata,
  data.frame(NoReads = apply(dat_blank$abund, 2, sum)),
  by = 0
)

ggplot(tabReads, aes(x = LibID, y = NoReads, colour = Kit)) +
  geom_jitter(width = .1) +
  theme(axis.text.x = element_text(angle = 90, vjust = -0.5)) +
  labs(x = "", y = "# of reads") +
  theme(legend.position = "none")
```

## QC - samples

```{r}
dat_types <- datraw %>%
  amp_subset_samples(!Soil_type %in% c("Blank", "Activated sludge") & !is.na(Kit))
```

Very uneven sequencing depth, hence we will have to remove the beach sand samples, or work with rarefied data. 

```{r reads and rarefraction plot}
tabReads <- merge(
  dat_types$metadata,
  data.frame(NumReads = apply(dat_types$abund, 2, sum)),
  by = 0
)

plot.reads <- tabReads %>%
  ggplot(aes(x = Soil_type, y = NumReads, color = Soil_type)) +
  facet_wrap(facets = vars(Protocol), nrow = 1) +
  geom_point(size = 5, alpha = 0.5) +
  theme(legend.position = "bottom") +
  labs(x = "", y = "# of reads") +
  scale_fill_manual(values = colors) +
  theme_bw(base_size = 10) +
  theme(
    legend.position = "right",
    axis.text.x = element_blank(),
    axis.text.y = element_text(face = "bold", size = 10),
    axis.title = element_blank(),
    axis.ticks.x = element_blank(),
    plot.margin = unit(c(0, 1, 0, 0), "cm"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 10),
    strip.text.x = element_text(size = 7, face = "bold"),
    strip.text.y = element_text(size = 7, face = "bold"),
    legend.title = element_text(face = "bold"),
    legend.text = element_text(face = "bold", size = 10)
  )

plot.reads

# Rarecurve for small and downscale. Do we need it?
plot.rarecurve <- amp_rarecurve(dat_types,
  facet_by = "Protocol",
  color_by = "Soil_type"
) +
  labs(y = "Number of observed ASVs") +
  scale_color_manual(values = alpha(colors, 0.5)) +
  theme_bw(base_size = 10) +
  labs(
    x = "",
    y = "",
    title = "Number of observed ASVs as function of sequencing depth"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.text.x = element_text(angle = 90, face = "bold", vjust = 0.5, size = 10),
    axis.text.y = element_text(face = "bold", size = 10),
    # plot.margin = unit(c(0, 1, 0, 0), "cm"),
    strip.background = element_blank()
  ) # ,
# strip.text.x = element_blank())

plot.rarecurve
```
